import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { SeedInputs } from '../shared/seed';

interface PdfData {
    jam3iyaName: string;
    amount: number;
    date: string;
    seed: string;
    inputs: SeedInputs;
    results: Array<{ month: number; memberName: string; score: string }>;
    id?: string; // Optional for backward compatibility, but highly recommended
}

const createPdfDoc = (data: PdfData) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    // Header
    doc.setFontSize(22);
    doc.setTextColor(99, 102, 241); // Indigo
    doc.text('Qor3a - Fair Draw Results', 105, 20, { align: 'center' });

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Name: ${data.jam3iyaName}`, 105, 32, { align: 'center' });

    // Subheader with ID
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    if (data.id) {
        doc.text(`ID: ${data.id}`, 105, 38, { align: 'center' });
    }

    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(`Amount: ${data.amount} | Date: ${data.date}`, 105, 45, { align: 'center' });

    // Results Table
    const tableData = data.results.map(r => [
        r.month.toString(),
        r.memberName,
        r.score.substring(0, 12) + '...'
    ]);

    autoTable(doc, {
        startY: 60,
        head: [['Month', 'Member', 'Score (Hash)']],
        body: tableData,
        theme: 'striped',
        headStyles: {
            fillColor: [99, 102, 241],
            textColor: [255, 255, 255],
            fontStyle: 'bold'
        },
        styles: {
            fontSize: 10,
            cellPadding: 5,
        },
        alternateRowStyles: {
            fillColor: [245, 245, 250]
        }
    });

    // Get final Y position after table
    const finalY = (doc as any).lastAutoTable?.finalY || 150;

    // Verification Section
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Verification Data', 14, finalY + 15);

    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);

    const verifyY = finalY + 22;
    if (data.id) {
        doc.text(`Jam3iya ID: ${data.id}`, 14, verifyY);
        doc.text(`SEED: ${data.seed}`, 14, verifyY + 5);
        doc.text(`Salt: ${data.inputs.salt || '(none)'}`, 14, verifyY + 10);
        doc.text(`Timestamp: ${data.inputs.timestamp}`, 14, verifyY + 15);

        if (data.inputs.externalEvent) {
            doc.text(`External Event: ${data.inputs.externalEvent}`, 14, verifyY + 20);
        }
    } else {
        doc.text(`SEED: ${data.seed}`, 14, verifyY);
        doc.text(`Salt: ${data.inputs.salt || '(none)'}`, 14, verifyY + 5);
        doc.text(`Timestamp: ${data.inputs.timestamp}`, 14, verifyY + 10);

        if (data.inputs.externalEvent) {
            doc.text(`External Event: ${data.inputs.externalEvent}`, 14, verifyY + 15);
        }
    }

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('This document can be verified by recalculating the SEED with the same inputs.', 105, 285, { align: 'center' });
    doc.text('Generated by Qor3a - Developed by Khribech', 105, 290, { align: 'center' });

    return doc;
};

const getSafeFilename = (name: string) => {
    return (name.replace(/[^\w\s-]/g, '').replace(/\s+/g, '_').substring(0, 30) || 'qor3a_results') + '.pdf';
}

export function generatePdf(data: PdfData) {
    try {
        const doc = createPdfDoc(data);
        const filename = getSafeFilename(data.jam3iyaName);
        const blob = doc.output('blob');
        const url = URL.createObjectURL(blob);

        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);

        setTimeout(() => {
            if (!document.hidden) window.open(url, '_blank');
        }, 100);

        setTimeout(() => URL.revokeObjectURL(url), 60000);
        return true;
    } catch (error) {
        console.error('Error generating PDF:', error);
        alert('حدث خطأ أثناء إنشاء ملف PDF.');
        return false;
    }
}

export async function sharePdf(data: PdfData) {
    try {
        const doc = createPdfDoc(data);
        const filename = getSafeFilename(data.jam3iyaName);
        const blob = doc.output('blob');
        const file = new File([blob], filename, { type: 'application/pdf' });

        if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
            await navigator.share({
                files: [file],
                title: 'نتيجة القرعة',
                text: `نتائج قرعة ${data.jam3iyaName}`
            });
            return true;
        } else {
            alert('متصفحك لا يدعم مشاركة الملفات مباشرة. يرجى تحميل الملف ثم إرساله.');
            return false;
        }
    } catch (error) {
        console.error('Error sharing PDF:', error);
        return false;
    }
}
